name: Check

on:
    push:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16.x"

            - name: Clean install
              run: npm ci

            - name: Build
              run: npm run build
